name: Changed Files

on:
#   workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Changed Files
    
    steps: 
      - name: Check out source repository
        uses: actions/checkout@v3
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.PAT }}
#           ignore: "**/*.js" # glob
          foldersOnly: true # to only include folders in the output
          format: json # either json, csv or newline
      - name: Echo
        run: echo ${{ steps.get_changed.outputs.changed }}
